In [2]:
import torch

In [9]:
x = torch.tensor([[1, 2], [3, 4.], [5, 6], [7, 8]])
config_paths = [[0, 1], [1, 2, 3]]

In [10]:
max_length = max(len(path) for path in config_paths)

# Pad shorter paths
padded_paths = [path + [-1]*(max_length - len(path)) for path in config_paths]

# Convert to tensor
padded_paths_tensor = torch.tensor(padded_paths, dtype=torch.long)


In [12]:
mask = (padded_paths_tensor != -1)

In [25]:
mask = torch.zeros(len(config_paths), x.shape[0], x.shape[1], dtype=torch.bool)
for i, path in enumerate(config_paths):
    mask[i, path, :] = 1

In [26]:
mask

tensor([[[ True,  True],
         [ True,  True],
         [False, False],
         [False, False]],

        [[False, False],
         [ True,  True],
         [ True,  True],
         [ True,  True]]])

In [44]:
(x.expand_as(mask) * mask).sum(dim=1) / torch.tensor([[2, 3]]).T

tensor([[2., 3.],
        [5., 6.]])

In [14]:
mask.unsqueeze(-1).expand(-1, -1, x.size(-1))

tensor([[[ True,  True],
         [ True,  True],
         [False, False]],

        [[ True,  True],
         [ True,  True],
         [ True,  True]]])

In [ ]:
x_gathered = torch.masked_select(x, mask.unsqueeze(-1).expand(-1, -1, x.size(-1)))

In [6]:
x[[0, 1, 3]]

tensor([[1., 2.],
        [3., 4.],
        [7., 8.]])

In [47]:
fn = lambda *xs: list(xs)

In [48]:
fn(1, 2, 3)

[1, 2, 3]