In [1]:
import numpy as np
from scipy.stats import kendalltau
from gfos.data.dataset import sample_configs


In [98]:
preds = np.random.randn(100000)
trues = np.random.randn(100000)

original_pred_order = np.argsort(preds)
original_true_order = np.argsort(trues)
original_tau, _ = kendalltau(original_pred_order, original_true_order)
print(original_tau)

sampled_trues = np.sort(trues)
indices = np.argsort(trues)
sampled_pred_order = np.argsort(preds[indices])
sampled_tau, _ = kendalltau(sampled_pred_order, np.argsort(sampled_trues))
print(sampled_tau)

0.001142048620486205
-0.0002292586925869259


In [58]:
sampled_trues

array([-4.6934168 , -4.20129095, -4.00875081, ...,  3.94666367,
        3.98346523,  4.12181249])

In [86]:
x = np.array([0, 1, 3, 6, 4, 5, 2])
y = np.array([3, 2, 5, 1, 4, 0, 6])
tau, _ = kendalltau(x, y)
tau

-0.33333333333333337

In [87]:
x = np.array([5, 6, 1, 3, 2, 0, 4])
y = np.array([0, 1, 2, 5, 6, 3, 4])
tau, _ = kendalltau(x, y)
tau

-0.33333333333333337

In [38]:
x = np.random.randn(10)
y = np.random.randn(10)

original_tau, _ = kendalltau(np.argsort(x), np.argsort(y))

y_order = np.argsort(y)
x_order = np.argsort(x)
y = y[y_order]
x = x[x_order[y_order]]
sorted_tau, _ = kendalltau(np.argsort(x), np.argsort(y))


In [33]:
np.argsort(y)

array([0, 1, 2, 3, 4])

In [39]:
original_tau, sorted_tau

(0.1111111111111111, -0.3333333333333333)

In [222]:
import torch

torch.manual_seed(42)

model = torch.nn.Linear(10, 1)
model.weight.data = torch.randn(1, 10)
x = torch.randn(5, 10, requires_grad=False)
y = torch.randn(5, requires_grad=False)

preds = model(x).detach().squeeze().numpy()
# print(np.argsort(preds), np.argsort(y))
tau, _ = kendalltau(np.argsort(preds), np.argsort(y))

print(tau)
permutation = torch.argsort(y)
x_ = x[permutation]
y_ = y[permutation]
pred_ = model(x_).detach().squeeze().numpy()
tau, _ = kendalltau(np.argsort(pred_), np.argsort(y_))
tau
print(tau)

-0.19999999999999998
-0.6


In [224]:
y, y_

(tensor([-0.3090, -0.4268,  0.4504, -0.0022, -0.1980]),
 tensor([-0.4268, -0.3090, -0.1980, -0.0022,  0.4504]))

In [225]:
preds, pred_

(array([ 5.2897863,  4.5470743, -2.9400432,  2.027326 , -0.5778932],
       dtype=float32),
 array([ 4.5470743,  5.2897863, -0.5778933,  2.027326 , -2.940043 ],
       dtype=float32))

In [226]:
np.argsort(preds), np.argsort(y)

(array([2, 4, 3, 1, 0]), tensor([1, 0, 4, 3, 2]))

In [227]:
np.argsort(pred_), np.argsort(y_)

(array([4, 2, 3, 0, 1]), tensor([0, 1, 2, 3, 4]))

In [228]:
kendalltau(preds, y), kendalltau(pred_, y_)

(SignificanceResult(statistic=-0.6, pvalue=0.23333333333333334),
 SignificanceResult(statistic=-0.6, pvalue=0.23333333333333334))