In [1]:
import numpy as np
from scipy.stats import kendalltau
from gfos.data.dataset import sample_configs


In [2]:
preds = np.random.randn(100000)
trues = np.random.randn(100000)

original_pred_order = np.argsort(preds)
original_true_order = np.argsort(trues)
original_tau, _ = kendalltau(original_pred_order, original_true_order)
print(original_tau)

sampled_trues = np.sort(trues)
indices = np.argsort(trues)
sampled_pred_order = np.argsort(preds[indices])
sampled_tau, _ = kendalltau(sampled_pred_order, np.argsort(sampled_trues))
print(sampled_tau)

0.0013118323183231835
0.0030735587355873568


In [3]:
sampled_trues

array([-4.05654908, -4.00978328, -3.98064967, ...,  4.18433393,
        4.40851797,  4.50967854])

In [4]:
x = np.array([0, 1, 3, 6, 4, 5, 2])
y = np.array([3, 2, 5, 1, 4, 0, 6])
tau, _ = kendalltau(x, y)
tau

-0.33333333333333337

In [5]:
x = np.array([5, 6, 1, 3, 2, 0, 4])
y = np.array([0, 1, 2, 5, 6, 3, 4])
tau, _ = kendalltau(x, y)
tau

-0.33333333333333337

In [6]:
x = np.random.randn(10)
y = np.random.randn(10)

original_tau, _ = kendalltau(np.argsort(x), np.argsort(y))

y_order = np.argsort(y)
x_order = np.argsort(x)
y = y[y_order]
x = x[x_order[y_order]]
sorted_tau, _ = kendalltau(np.argsort(x), np.argsort(y))


In [7]:
np.argsort(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [8]:
original_tau, sorted_tau

(-0.15555555555555553, -0.19999999999999998)

In [9]:
import torch

torch.manual_seed(42)

model = torch.nn.Linear(10, 1)
model.weight.data = torch.randn(1, 10)
x = torch.randn(5, 10, requires_grad=False)
y = torch.randn(5, requires_grad=False)

preds = model(x).detach().squeeze().numpy()
# print(np.argsort(preds), np.argsort(y))
tau, _ = kendalltau(np.argsort(preds), np.argsort(y))

print(tau)
permutation = torch.argsort(y)
x_ = x[permutation]
y_ = y[permutation]
pred_ = model(x_).detach().squeeze().numpy()
tau, _ = kendalltau(np.argsort(pred_), np.argsort(y_))
tau
print(tau)

-0.19999999999999998
-0.6


In [10]:
y, y_

(tensor([-0.3090, -0.4268,  0.4504, -0.0022, -0.1980]),
 tensor([-0.4268, -0.3090, -0.1980, -0.0022,  0.4504]))

In [11]:
preds, pred_

(array([ 5.289787  ,  4.547075  , -2.9400432 ,  2.0273263 , -0.57789314],
       dtype=float32),
 array([ 4.547075  ,  5.289787  , -0.57789326,  2.0273263 , -2.940043  ],
       dtype=float32))

In [12]:
np.argsort(preds), np.argsort(y)

(array([2, 4, 3, 1, 0], dtype=int64), tensor([1, 0, 4, 3, 2]))

In [13]:
np.argsort(pred_), np.argsort(y_)

(array([4, 2, 3, 0, 1], dtype=int64), tensor([0, 1, 2, 3, 4]))

In [14]:
kendalltau(preds, y), kendalltau(pred_, y_)

(SignificanceResult(statistic=-0.6, pvalue=0.23333333333333334),
 SignificanceResult(statistic=-0.6, pvalue=0.23333333333333334))

In [15]:
kendalltau(np.argsort(preds), np.argsort(y)), kendalltau(np.argsort(pred_), np.argsort(y_))

(SignificanceResult(statistic=-0.19999999999999998, pvalue=0.8166666666666667),
 SignificanceResult(statistic=-0.6, pvalue=0.23333333333333334))